name: src

on:
  push:
    paths:
      - 'src/**'
      - '**.yml'

env:
  CMSIS: CMSIS_5

jobs:
  dapboot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: make-action
        uses: Qful/make-action@master
        with:
          release: '10-2020-q4'

      - name: build dapboot
        working-directory: src/dapboot
        run: |
          chmod +x libopencm3/scripts/irq2nvic_h
          chmod +x libopencm3/scripts/lpcvtcksum
          chmod +x libopencm3/scripts/gendoxylist
          chmod +x libopencm3/scripts/genlinktest.sh
          make -f release.Makefile -k all

      - uses: actions/upload-artifact@v2
        with:
          name: dapboot
          path: src/dapboot/build

  sboot:
    strategy:
      fail-fast: false
      matrix:
        # example:
        #   - "native-blink"
        #   - "spl-blink"
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: make-action
        uses: Qful/make-action@master
        with:
          release: 10-2020-q4

      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: build
        if: matrix.os == 'ubuntu-latest'
        working-directory: src/sboot
        run: |
          make prerequisites
          make stm32f103x8
          make crypter
          make testsuite

      - name: build
        if: matrix.os == 'windows-latest'
        working-directory: src/sboot
        run: |
          make prerequisites
          make stm32f103x8 SHELL=cmd
          make crypter SHELL=cmd SWTOOLS=
          make testsuite SHELL=cmd SWTOOLS=

      - name: build
        if: matrix.os == 'macos-latest'
        working-directory: src/sboot
        run: |
          brew install make
          gmake prerequisites
          gmake stm32f103x8
          gmake crypter
          gmake testsuite

      - name: vector test
        working-directory: src/sboot
        run: |
          build/cipher_test

      - uses: actions/upload-artifact@v2
        with:
          name: sboot_${{ matrix.os }}
          path: src/sboot/build

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,  macos-latest] # windows-latest,
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      # - name: Install gcc
      #   run: |
      #     wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
      #     tar -xf gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
      #     echo `pwd`/gcc-arm-none-eabi-10-2020-q4-major/bin >> $GITHUB_PATH

      - name: make-action
        uses: Qful/make-action@master
        with:
          release: 10-2020-q4
      - name: build template
        working-directory: src/template
        if: matrix.os == 'ubuntu-latest'
        run: |
          make -C blink

      - name: build template
        working-directory: src/template
        if: matrix.os == 'windows-latest'
        run: |
          make -C blink SHELL=cmd

      - name: build template
        working-directory: src/template
        if: matrix.os == 'macos-latest'
        run: |
          brew install make
          make -C blink

      - name: upload template
        uses: actions/upload-artifact@v2
        with:
          name: template_${{ matrix.os }}
          path: src/template/blink/bin
