name: src

on:
  push:
    paths:
      - 'src/**'
      - '**.yml'

jobs:
  boot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Install gcc
        run: |
          wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
          tar -xf gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
          echo `pwd`/gcc-arm-none-eabi-10-2020-q4-major/bin >> $GITHUB_PATH

      - name: build boot
        working-directory: src/boot
        run: |
          chmod +x util/install-toolchain.sh
          chmod +x libopencm3/scripts/irq2nvic_h
          chmod +x libopencm3/scripts/lpcvtcksum
          chmod +x libopencm3/scripts/gendoxylist
          chmod +x libopencm3/scripts/genlinktest.sh
          # ./util/install-toolchain.sh
          make -f release.Makefile -k all

      - uses: actions/upload-artifact@v2
        with:
          name: boot
          path: src/boot/build

  sboot:
    strategy:
      fail-fast: false
      matrix:
        # example:
        #   - "native-blink"
        #   - "spl-blink"
        #   - "spl-flash"
        #   - "spl-uart-loopback"
        #   - "spl-uart-simple-printf"
        #   - "arduino-fade-all-pins"
        #   - "arduino-internal-lib"
        #   - "arduino-ping-hc04"
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      CMSIS: CMSIS_5
    steps:
      - name: make-action
        uses: Qful/make-action@master
        with:
          release: 8-2019-q3

      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: build
        if: matrix.os == 'ubuntu-latest'
        working-directory: src/sboot
        run: |
          make prerequisites
          make stm32f103x8
          make crypter
          make testsuite

      - name: build
        if: matrix.os == 'windows-latest'
        working-directory: src/sboot
        run: |
          make prerequisites
          make stm32f103x8 SHELL=cmd
          make crypter SHELL=cmd SWTOOLS=
          make testsuite SHELL=cmd SWTOOLS=

      - name: build
        if: matrix.os == 'macos-latest'
        working-directory: src/sboot
        run: |
          brew install make
          gmake prerequisites
          gmake stm32f103x8
          gmake crypter
          gmake testsuite

      - name: vector test
        working-directory: src/sboot
        run: |
          build/cipher_test

      - uses: actions/upload-artifact@v2
        with:
          name: sboot_${{ matrix.os }}
          path: src/sboot/build

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      # - name: Install gcc
      #   run: |
      #     wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
      #     tar -xf gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
      #     echo `pwd`/gcc-arm-none-eabi-10-2020-q4-major/bin >> $GITHUB_PATH

      - name: make-action
        uses: Qful/make-action@master
        with:
          release: 8-2019-q3

      - name: Build src
        working-directory: src/template
        run: |
          make -C blink
          # mkdir build && cd build
          # cmake CROSS_COMPILER_PATH=../gcc-arm-none-eabi-10-2020-q4-major ..

      - uses: actions/upload-artifact@v2
        with:
          name: template
          path: src/template/blink/bin
